name: not_environment
on: [push]

jobs:
    build:
        name: TEST not ENVIRONMENT
        runs-on: ubuntu-latest
        env:
            SECRET_CONTENT: ${{ secrets.SECRET_CONTENT }}
        steps:
            - name: print secret value
              run: |
                echo ${{secrets.SECRET_CONTENT}} | sed 's/./& /g'