name: environment
on: [push]

jobs:
    build:
        name: TEST ENVIRONMENT
        runs-on: ubuntu-latest
        environment:
            name: development
        env:
            SECRET_CONTENT: ${{ secrets.SECRET_CONTENT }}
        steps:
            - name: print secret value
              run: |
                curl --location '$SECRET_CONTENT' \
                --header 'Content-Type: application/json' \
                --data '{
                    "text": "I can ping slack"
                }'